name: Deploy
on:
  push:
    tags:
      - v*
env:
  NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/
      - name: Register NPM Token
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > /home/runner/work/_temp/.npmrc
          echo "_auth=$NPM_TOKEN" >>  /home/runner/work/_temp/.npmrc
          echo "email=$NPM_EMAIL" >>  /home/runner/work/_temp/.npmrc
          echo "always-auth=true" >>  /home/runner/work/_temp/.npmrc
      - name: NPM Install
        run: npm install
      - name: Build
        run: npm run build
      - name: NPM Publish
        run: npm publish